# https://scrutinizer-ci.com/docs/configuration/build_reference
build:
  image: default-bionic
  environment:
    timezone: UTC
    php:
      version: "8.1"
      ini:
        memory_limit: "-1"
  tests:
    override:
      - command: php-scrutinizer-run
        idle_timeout: 14400
      - command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'coverage.xml'
          format: 'clover'
      ## - command: phpcs-run
      ##   idle_timeout: 14400

# https://scrutinizer-ci.com/docs/reviews/excluding_files_from_analysis
filter:
  paths:
    - 'htdocs/**'
    - 'Core/**'
    - 'Modules/**'
    - 'Deprecated/**'
  exclude_paths:
    - 'test'
  dependency_paths:
    - vendor/
    - includes/

# Configure code duplication scans, if relevant
checks:
  php:
    duplication:
      enabled: true
      config:
        threshold: 70

# Code analysis settings, if you need them
coding_style:
  php:
    enabled: true

# https://scrutinizer-ci.com/docs/configuration/build_status
# build_failure_conditions:

# Configuración de herramientas de análisis específicas, si es necesario
tools:
  external_code_coverage:
    timeout: 600
  php_code_sniffer:
    config:
      standard: 'PSR-2'

# https://scrutinizer-ci.com/docs/configuration/credentials
# credentials:
