filter:
  paths:
    - 'htdocs/**'
    - 'Core/**'
    - 'Modules/**'
    - 'Deprecated/**'

# Opcional: especifica las ramas que quieres analizar
branches:
  except:
    - legacy

# Configuración de herramientas de análisis específicas, si es necesario
tools:
  external_code_coverage:
    timeout: 600
  php_code_sniffer:
    config:
      standard: 'PSR-2'

# Configura los análisis de duplicación de código, si es relevante
checks:
  php:
    duplication:
      enabled: true
      config:
        threshold: 70

# Ajustes de análisis de código, si lo necesitas
coding_style:
  php:
    enabled: true

# Configura la recopilación de cobertura de código, si la usas
build:
  image: default-bionic
  environment:
    analysis:
      php: 8.1
  tests:
    override:
      - command: php-scrutinizer-run
        idle_timeout: 14400
      - command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'coverage.xml'
          format: 'clover'
      ## - command: phpcs-run
      ##   idle_timeout: 14400
